openapi: 3.0.0
info:
  title: "apifotopessoa"
  description: "apifotopessoa"
  version: "20250408010304"
servers:
  - url: http://localhost:8080/projetogenexus/apifotopessoa
security:
  - bearerAuth: []
paths:
  /gxobject:
    post:
      tags:
        - api
      operationId: "UploadImagemDireta"
      summary: "Faz upload direto de uma imagem no corpo da requisição"
      requestBody:
        required: true
        content:
          image/png:
            schema:
              type: string
              format: binary
          image/jpeg:
            schema:
              type: string
              format: binary
          image/jpg:
            schema:
              type: string
              format: binary
          image/gif:
            schema:
              type: string
              format: binary
      responses:
        200:
          description: "Upload realizado com sucesso"
        400:
          description: "Requisição inválida"
        500:
          description: "Erro interno no servidor"
  /:
    post:
      tags:
        - apifotopessoa  
      operationId: "apifotopessoa.MetodoInserirFoto"
      summary: "Metodo para fazer uploaad da foto"
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MetodoInserirFotoInput"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/GeneXus.Common.Messages_Message"  

        404:
          description: "Not found"


    get:
      tags:
        - apifotopessoa  
      operationId: "apifotopessoa.MetodoConsultartFoto"
      summary: "Método para consultar foto da pessoa"
      parameters:
        - name: "Pesid"
          in: "query"
          required: false
          schema:
            type: "integer"
            format: "int64"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: "string"


        404:
          description: "Not found"

components:
  schemas:
    MetodoInserirFotoInput:  
      properties:
        crud_foto_pessoa_post_sdt:
          description: "crud_foto_pessoa_post_sdt"
          $ref: "#/components/schemas/crud_foto_pessoa_post_sdt"

  
    crud_foto_pessoa_post_sdt:
      properties:
        pes_id:
          description: "pes_id"
          type: "integer"
          format: "int64"
        fp_foto:
          description: "fp_foto"
          type: "string"



    GeneXus.Common.Messages_Message:
      properties:
        Id:
          description: "Id"
          type: "string"
        Type:
          description: "Type"
          type: "integer"
          format: "int32"
        Description:
          description: "Description"
          type: "string"

  securitySchemes:  
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT


 
