openapi: 3.0.0
info:
  title: "apiservidorefetivo"
  description: "apiservidorefetivo"
  version: "20250401040410"
servers:
  - url: http://localhost:8080/projetojava/apiservidorefetivo
paths:
  /:
    post:
      tags:
        - apiservidorefetivo  
      operationId: "apiservidorefetivo.MetodoInserirServidorEfetivo"
      summary: "Metodo para cadastar servidor efetivo"
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MetodoInserirServidorEfetivoInput"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/GeneXus.Common.Messages_Message"  

        404:
          description: "Not found"


    get:
      tags:
        - apiservidorefetivo  
      operationId: "apiservidorefetivo.MetodoConsultarServidorEfetivo"
      summary: "Método para consultar servidor efetivo."
      parameters:
        - name: "pesid"
          in: "query"
          required: false
          schema:
            type: "integer"
            format: "int64"
        - name: "Pagina"
          in: "query"
          required: false
          schema:
            type: "integer"
            format: "int32"
        - name: "Quantidadepagina"
          in: "query"
          required: false
          schema:
            type: "integer"
            format: "int32"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MetodoConsultarServidorEfetivoOutput"
        404:
          description: "Not found"


    put:
      tags:
        - apiservidorefetivo  
      operationId: "apiservidorefetivo.MetodoAlterarServidorEfetivo"
      summary: "Método para alterar servidor efetivo"
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MetodoAlterarServidorEfetivoInput"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/GeneXus.Common.Messages_Message"  

        404:
          description: "Not found"

  /{pesid}:
    delete:
      tags:
        - apiservidorefetivo  
      operationId: "apiservidorefetivo.MetodoExcluirServidorEfetivo"
      summary: "Método para excluir servidor efetivo"
      parameters:
        - name: "pesid"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/GeneXus.Common.Messages_Message"  

        404:
          description: "Not found"
components:
  schemas:
    MetodoConsultarServidorEfetivoOutput:
      properties:
        crud_servidor_efetivo_get_sdt:
          description: "crud_servidor_efetivo_get_sdt"
          type: array
          items:
            $ref: "#/components/schemas/crud_servidor_efetivo_get_sdt"
        Messages:
          description: "Messages"
          type: array
          items:
            $ref: "#/components/schemas/GeneXus.Common.Messages_Message"



    MetodoInserirServidorEfetivoInput:  
      properties:
        crud_servidor_efetivo_post_sdt:
          description: "crud_servidor_efetivo_post_sdt"
          $ref: "#/components/schemas/crud_servidor_efetivo_post_sdt"


    MetodoAlterarServidorEfetivoInput:  
      properties:
        crud_servidor_efetivo_put_sdt:
          description: "crud_servidor_efetivo_put_sdt"
          $ref: "#/components/schemas/crud_servidor_efetivo_put_sdt"

  
    crud_servidor_efetivo_post_sdt:
      properties:
        se_matricula:
          description: "se_matricula"
          type: "string"
        pes_nome:
          description: "pes_nome"
          type: "string"
        pes_data_nascimento:
          description: "pes_data_nascimento"
          type: "string"
          format: "date"
        pes_sexo:
          description: "pes_sexo"
          type: "string"
        pes_mae:
          description: "pes_mae"
          type: "string"
        pes_pai:
          description: "pes_pai"
          type: "string"
        end_tipo_endereco:
          description: "end_tipo_endereco"
          type: "string"
        end_logradouro:
          description: "end_logradouro"
          type: "string"
        end_numero:
          description: "end_numero"
          type: "integer"
          format: "int64"
        end_bairro:
          description: "end_bairro"
          type: "string"
        cid_nome:
          description: "cid_nome"
          type: "string"
        cid_uf:
          description: "cid_uf"
          type: "string"



    GeneXus.Common.Messages_Message:
      properties:
        Id:
          description: "Id"
          type: "string"
        Type:
          description: "Type"
          type: "integer"
          format: "int32"
        Description:
          description: "Description"
          type: "string"



    crud_servidor_efetivo_get_sdt:
      properties:
        se_pes_id:
          description: "se_pes_id"
          type: "integer"
          format: "int64"
        se_matricula:
          description: "se_matricula"
          type: "string"
        pes_nome:
          description: "pes_nome"
          type: "string"
        pes_data_nascimento:
          description: "pes_data_nascimento"
          type: "string"
          format: "date"
        pes_sexo:
          description: "pes_sexo"
          type: "string"
        pes_mae:
          description: "pes_mae"
          type: "string"
        pes_pai:
          description: "pes_pai"
          type: "string"
        end_tipo_endereco:
          description: "end_tipo_endereco"
          type: "string"
        end_logradouro:
          description: "end_logradouro"
          type: "string"
        end_numero:
          description: "end_numero"
          type: "integer"
          format: "int64"
        end_bairro:
          description: "end_bairro"
          type: "string"
        cid_nome:
          description: "cid_nome"
          type: "string"
        cid_uf:
          description: "cid_uf"
          type: "string"



    crud_servidor_efetivo_put_sdt:
      properties:
        se_pes_id:
          description: "se_pes_id"
          type: "integer"
          format: "int64"
        se_matricula:
          description: "se_matricula"
          type: "string"
        pes_data_nascimento:
          description: "pes_data_nascimento"
          type: "string"
          format: "date"
        pes_sexo:
          description: "pes_sexo"
          type: "string"
        pes_mae:
          description: "pes_mae"
          type: "string"
        pes_pai:
          description: "pes_pai"
          type: "string"
        end_id:
          description: "end_id"
          type: "integer"
          format: "int64"



 
