openapi: 3.0.0
info:
  title: "apivalidacao"
  description: "apivalidacao"
  version: "20250401040410"
servers:
  - url: http://localhost:8080/projetojava/apivalidacao
paths:
  /login:
    post:
      tags:
        - apivalidacao  
      operationId: "apivalidacao.LoginUsuario"
      summary: "Método gerar o token"
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginUsuarioInput"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginUsuarioOutput"
        404:
          description: "Not found"

components:
  schemas:
    LoginUsuarioOutput:
      properties:
        Token:
          type: "string"
        Messages:
          description: "Messages"
          type: array
          items:
            $ref: "#/components/schemas/GeneXus.Common.Messages_Message"

    LoginUsuarioInput:  
      properties:
        Login:
          type: "string"
        Senha:
          type: "string"
  
    GeneXus.Common.Messages_Message:
      properties:
        Id:
          description: "Id"
          type: "string"
        Type:
          description: "Type"
          type: "integer"
          format: "int32"
        Description:
          description: "Description"
          type: "string"



 
